Added a cross button for deleting appointments by patient himself.
devlup-labs/hms-iitj pull request #21
Opened 2021-03-02 15:45 UTC by vedthakur5

2021-03-16 19:57 UTC, harsh-not-haarsh commented
Hey @vedthakur5 
Can you add some relevant screen shots?

2021-03-17 16:15 UTC, vedthakur5 commented
![a](https://user-images.githubusercontent.com/64027060/111500425-ffed7500-8769-11eb-8c9e-1c8a4cbe82a3.png)
![Screenshot 2021-03-17 161516](https://user-images.githubusercontent.com/64027060/111500514-172c6280-876a-11eb-9ac0-4c1bb0607266.png)
These are some screenshots

2021-03-17 18:47 UTC, harsh-not-haarsh requested changes

2021-03-17 18:47 UTC, harsh-not-haarsh commented on hc/urls.py
> +    re_path(r'^cancelAppointment/(?P<pk>[0-9]+)/$', cancelAppointment, name='cancelAppointment'),
if you can do this with path only

2021-03-17 18:47 UTC, harsh-not-haarsh commented on hc/views/views_patient.py
> +def cancelAppointment(request, pk):
rename the pk to apId or something like that

2021-03-17 18:47 UTC, harsh-not-haarsh commented on templates/main/index.html
> +                    <script src="{% static '/js/test.js' %}" type="text/javascript"></script>
remove this

2021-03-18 07:14 UTC, vedthakur5 commented
created a new pr #22

2021-03-20 17:36 UTC, harsh-not-haarsh approved these changes

2021-03-20 17:37 UTC, merged